[package]
name = "RustBert"
version = "0.1.0"
authors = ["philschmid <schmidphilipp1995@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.14.0"

# [dev-dependencies]
# anyhow = "1.0.38"