FROM rust:1 AS build
RUN apt-get update && apt-get cmake libgomp1 locales locales-all clang -y
RUN locale-gen en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8

WORKDIR /usr/src
RUN git clone https://github.com/microsoft/onnxruntime.git onnxruntime
RUN USER=root cargo new my-app
RUN mkdir -p /usr/src/my-app/target/onnxruntime
WORKDIR /usr/src/onnxruntime
RUN git checkout v1.5.2
RUN ./build.sh --config RelWithDebInfo --build_shared_lib --parallel --cmake_extra_defines="CMAKE_INSTALL_PREFIX=/usr/src/my-app/target/onnxruntime"

WORKDIR build/Linux/RelWithDebInfo
RUN make install
WORKDIR /usr/src/my-app
COPY Cargo.toml Cargo.lock ./
COPY src ./src
ENV ONNXRUNTIME_INSTALL_DIR=/usr/src/my-app/target/onnxruntime
ENV ORT_LIB_LOCATION=/usr/src/my-app/target/onnxruntime
ENV ORT_STRATEGY=system
RUN cargo build --release